FROM python:3.12-slim

WORKDIR /app

# Install dependencies during build
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY start.sh /scripts/start.sh
RUN chmod +x /scripts/start.sh

EXPOSE 8888

CMD ["/scripts/start.sh"]
